### ISSUE TITLE
Файлы для graphics.h

### ISSUE THREAD

**Issue by Maksim-Bakharev** [Maksim-Bakharev/Cours-work#2]
Скачать libgraph-1.0.2.tar.gz, разархивировать и сделать commit

**Comment by Andrew-Pashchenko** [comment]
Парни, отправьте ссылку для скачивания библиотеки graphics.h на ubuntu.
Спасибо.

**Comment by Maksim-Bakharev** [comment]
Андрей, держи
http://download.savannah.gnu.org/releases/libgraph/libgraph-1.0.2.tar.gz
