### ISSUE TITLE
Функции рисования самого игрока

### ISSUE THREAD

**Issue by Maksim-Bakharev** [Maksim-Bakharev/Cours-work#6]
Я думаю, что нужно написать 4 функции положения игрока (вправо, влево, вниз и вверх). 
Как считаете?

**Comment by yellown1gga** [comment]
Да, скорее всего можно "мордочку" пакмана перерисовывать в четырёх положениях, для наглядности. Так мы будем видеть, в какую сторону смотрит пакман и куда был совершен последний ход.

**Comment by Maksim-Bakharev** [comment]
Ну окей, попробую так сделать
