### ISSUE TITLE
Таблица рекордов

### ISSUE THREAD

**Issue by Maksim-Bakharev** [Maksim-Bakharev/Cours-work#8]
Макс, я думаю, что нужно файл создавать при первом запуске в котором будет время игры и имя. Ну и потом можно отсортировать строки по времени пузырьком обычным.

**Comment by Andrew-Pashchenko** [comment]
Так получается, что нужно в массив забивать значения времени типа float?
А имена как привязать ко времени?

**Comment by Maksim-Bakharev** [comment]
Короче оставим это на конец. Если время останется, подумаем как реализовать
